### ISSUE TITLE
suspicious code

### ISSUE THREAD

**Issue by em1xq** [Prescoter/Emora-Project#2]

**Comment by Prescoter** [comment]
Hey!
Thanks for warning me, there were indeed a few false positives from several antivirus programs, so I've updated the setup with fewer false detections.
Have a nice day.

**Comment by em1xq** [comment]
i understand the false positivies on virustotal, they could be present with certification problems.

but what about after installation i got mega cool file and its startup service on my virtual machine kekw
seems like a xmr monero miner with autorecovery after deleting
![image](https://github.com/Prescoter/Emora-Project/assets/73615575/cd944a02-5e04-4fa7-aebf-38757d7c0e56)
![image](https://github.com/Prescoter/Emora-Project/assets/73615575/e7762b90-c142-4224-b392-a71753a77e83)

https://www.virustotal.com/gui/file/cc3230597592601da33d133201d51badd908708ceec15ab4a5777d9759fbb1e6/details

**Comment by em1xq** [comment]
how's that

**Comment by em1xq** [comment]
My brother , i have nothing to do with your situation, but you better check the setup.exe that a person makes for you, because it's totally infected with a miner malware,

**Comment by Prescoter** [comment]
Okay, in that case thank you very much for warning me, problems like this won't happen again I think.
